
# comprehensive github action yml reference: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

---
name: CI

on:
  push: # any push event to master will trigger this
    branches: ["master"]
  pull_request: # any pull request to master will trigger this
    branches: ["master"]
  workflow_dispatch: # allows you to manually trigger run

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "${{ matrix.os }}" # for all available VM runtime, see this: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
    env: # define environment variables
      USING_COVERAGE: "3.6,3.7,3.8,3.9"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        exclude:
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.9
    steps:
      - uses: "actions/checkout@v2" # https://github.com/marketplace/actions/checkout
      - uses: "actions/setup-python@v2" # https://github.com/marketplace/actions/setup-python
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies on MacOS or Linux"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel virtualenv codecov
          pip install .
          pip install -r requirements-test.txt
        if: ${{ matrix.os == "ubuntu-latest" }}

      - name: "Install dependencies on MacOS or Linux"
        run: |
          python -m site
          python -m pip install --upgrade pip setuptools wheel virtualenv codecov
          pip install .
          pip install -r requirements-test.txt
        if: ${{ matrix.os == "windows-latest" }}

      - name: "Run pytest"
        run: "python -m pytest tests --cov=pathlib_mate"

      - name: "Upload coverage to Codecov"
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v1" # https://github.com/marketplace/actions/codecov-action
        with:
          fail_ci_if_error: true
